batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202412291722
train_epochs: 50
train_workers: 20
vocab: LeEvDA&nrMfkKSqN2:1"Gg0;'W(.uH6TYpZ9ywh)stBibF5!7VaUxj,RdI8-3*cOJ?4/loz+XQmP#C
width: 128
