batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202412291612
train_epochs: 1000
train_workers: 20
vocab: M+Z*Tu3Q9iYlO!/vgaN;C'r)VjmXJq6D:2dsSR8Wx57L#FeUAcBfh-z?kK4&yGI0.PHwbon,Et1"p(
width: 128
