batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202412291652
train_epochs: 1000
train_workers: 20
vocab: e;n?j"RY0oIH36aCXD)Avi!z.8bFG+OdfPMhquBJ1NcgEU-L5t,*VxK2'mrW/QwlZS9(7ksT4:yp#&
width: 128
