batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202412292206
train_epochs: 10
train_workers: 20
vocab: '&8YB9!zTH*a3WgQeZJK4:1q0FXP-y?l2cr/Mn,SRbsU''#LuI+m;x7NCd)pw(6fEGAV5"tvO.kDoihj'
width: 128
