batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202412291620
train_epochs: 1000
train_workers: 20
vocab: 0zL&.tB3IRYs#awMfmjpKu+Q(4:lbNXh5A"Crkcn8)U,!91yiODqTH'Fo*ZE/SGeg?72PWdxJ-Vv;6
width: 128
