batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202412291617
train_epochs: 1000
train_workers: 20
vocab: NPiwBKGgWxD3jZn#ze*k-!b27J/tHd;u,py8VYAM1f'"?(+l&h:C)TF.OmrRcaIU40vSLo9XqEQ6s5
width: 128
