batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202412292208
train_epochs: 10
train_workers: 20
vocab: 1D-p'NyO?/Fae+l:rQfuHM!J&ibv26czTEjxIGk;XY,hZ.58wU7*BgRAt)Vm9KSWo"C0P#q(d4snL3
width: 128
